version: '3.8'

services:
  # Aplicação PHP/Laravel
  app:
    image: php:8.2-fpm
    working_dir: /var/www
    volumes:
      - app_data:/var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - cardapy_network
    depends_on:
      - db
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # Servidor Web Nginx
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - app_data:/var/www
      - nginx_config:/etc/nginx/conf.d
    networks:
      - cardapy_network
    depends_on:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # Banco de dados MySQL (Principal)
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cardapy
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: cardapy_password
      MYSQL_USER: cardapy_user
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cardapy_network
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # Redis (Cache e Sessões)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cardapy_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  cardapy_network:
    driver: overlay
    attachable: true

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  app_data:
    driver: local
  nginx_config:
    driver: local 