version: '3.8'

services:
  # Aplicação PHP/Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cardapy_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - cardapy_network
    depends_on:
      - db
      - redis

  # Servidor Web Nginx
  webserver:
    image: nginx:alpine
    container_name: cardapy_webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cardapy_network
    depends_on:
      - app

  # Banco de dados MySQL (Principal)
  db:
    image: mysql:8.0
    container_name: cardapy_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cardapy
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: cardapy_password
      MYSQL_USER: cardapy_user
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cardapy_network
    command: --default-authentication-plugin=mysql_native_password

  # Redis (Cache e Sessões)
  redis:
    image: redis:7-alpine
    container_name: cardapy_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cardapy_network

networks:
  cardapy_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local 