version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 200M

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=cardapy
      - MYSQL_USER=cardapy
      - MYSQL_PASSWORD=cardapy123
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.8'
          memory: 800M

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 150M

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 150M

volumes:
  mysql_data:
  redis_data: 