version: '3.8'

services:
  webserver:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    networks:
      - cardapy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cardapy
      MYSQL_ROOT_PASSWORD: CardapyRoot123!
      MYSQL_PASSWORD: CardapyUser123!
      MYSQL_USER: cardapy_user
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cardapy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - cardapy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    command: redis-server --appendonly yes

  adminer:
    image: adminer:latest
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    networks:
      - cardapy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.2'
          memory: 128M

networks:
  cardapy-net:
    external: true

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local 