version: '3.8'

services:
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - cardapy_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cardapy
      MYSQL_ROOT_PASSWORD: CardapyRoot123!
      MYSQL_PASSWORD: CardapyUser123!
      MYSQL_USER: cardapy_user
    networks:
      - cardapy_network
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    networks:
      - cardapy_network
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    command: redis-server --appendonly yes

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - cardapy_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.2'
          memory: 128M

networks:
  cardapy_network:
    driver: overlay
    attachable: true

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

configs:
  nginx_config:
    external: false
    file: ./docker/nginx/default.conf 