version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    deploy:
      replicas: 1

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1

  cache:
    image: redis:alpine
    deploy:
      replicas: 1

  admin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
    deploy:
      replicas: 1

volumes:
  db_data: 